### PR TITLE
Adds functionality to do injections, split and save strain data and other channels into shorter frames so…

### PR DESCRIPTION
**Pull request by bhooshan-gadre**
… as to be used in onlive testing.

### CODE REVIEW

**Comment by ahnitz** [comment]
@bhooshan-gadre Any reason not to use the standard strain module from_cli as the starting point? That way you could also produce data with injections, fake noise, etc with this script.

**Comment by bhooshan-gadre** [comment]
@ahnitz I will do that eventually. Just did this to quickly test live autogating with BNS.

**Comment by bhooshan-gadre** [comment]
I think, I will add that to the pycbc_condition_strain. This is quick-fix till then.

**Comment by bhooshan-gadre** [comment]
Also, `pycbc_condition_strain` just writes 1 channel to the frame. I would like to keep other DQ channels with the new frame files.

**Comment by bhooshan-gadre** [comment]
Strain injection setup is added. Also matplotlib with agg backend.

**Comment by bhooshan-gadre** [comment]
The split frame can be added to `pycbc_condition_strain`. For now, keeping this separate.

**Comment by titodalcanton** [comment]
Seems ok to me. I assume this is still being used for injections, and more people may benefit from it.

**Pull request merged**
